Unit test + fix for state file handling in #115
facebook/taste-tester pull request #124
Opened 2019-08-19 21:33 UTC by malmond77

Two parts:

1. Demonstrate the bug in a unit test
2. Fix the bug

2019-08-19 21:47 UTC, jaymzh requested changes
JSON forces all keys to strings.
Mash forces all keys to be consistent.

The existing code fixes the bug I opened.... and I don't see this showing any legitimate bug, it's just doing the same work manually.

2019-08-26 22:57 UTC, nikitakoshikov approved these changes

2019-08-26 22:57 UTC, nikitakoshikov approved these changes

2019-08-26 22:59 UTC, nikitakoshikov approved these changes

2019-08-26 23:00 UTC, nikitakoshikov approved these changes

2026-02-20 21:35 UTC, jaymzh commented
Based on my comment, I still believe this is a no-op. No changes in 7 years, closing.

2026-02-20 21:35 UTC, closed without merging